version: "3.8"

services:
  web:
    image: web
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 9090 --reload"
    volumes:
      - ./src:/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    restart: always
    env_file:
      - dev.env
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15.1
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    env_file:
      - dev.env
    ports:
      - "6666:5432"
    restart: always


  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  celery:
    image: web
    restart: always
    command: celery -A app.infrastructure.workflows.worker worker -l info
    volumes:
     - .:/usr/bot/app
    env_file:
      - dev.env
    depends_on:
      - db
      - redis
#
  dashboard:
    build:
      context: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --address=0.0.0.0
    expose:
      - 5555
    env_file:
      - dev.env
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery


volumes:
  postgres_data: