version: "3.8"

services:
  web:
    image: web
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 9090 --reload
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    restart: always
    env_file:
      - .env_dev
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1

  db:
    image: postgres:15.1
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    env_file:
      - .env_dev
    ports:
      - "6666:5432"
    restart: always


volumes:
  postgres_data: