name: Lint and check types

on: [push, pull_request]
env:
  POETRY_HOME: /opt/poetry
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install poetry
      run: |
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.4.0

    - name: Validate the structure of the pyproject.toml
      run: |
         $POETRY_HOME/bin/poetry check

    - name: Verify that poetry.lock is consistent with pyproject.toml
      run: |
         $POETRY_HOME/bin/poetry lock --check

    - name: Install dependencies
      run: |
         $POETRY_HOME/bin/poetry install

    - name: Check code formatting by black
      run: |
        $POETRY_HOME/bin/poetry run black --check --verbose .

    - name: Lint code by ruff
      run: |
        $POETRY_HOME/bin/poetry run ruff .


    - name: Test with pytest
      run: |
        docker compose up -e EMAIL__LOGIN=${{ secrets.EMAIL_LOGIN }} -e EMAIL__PASSWORD=${{ secrets.EMAIL_PASSWORD }}  --build
        docker compose exec web bash
        pytest -v -s
