name: Lint and check types

on: [push, pull_request]
env:
  POETRY_HOME: /opt/poetry
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install poetry
      run: |
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.4.0

    - name: Validate the structure of the pyproject.toml
      run: |
         $POETRY_HOME/bin/poetry check

    - name: Verify that poetry.lock is consistent with pyproject.toml
      run: |
         $POETRY_HOME/bin/poetry lock --check

    - name: Install dependencies
      run: |
         $POETRY_HOME/bin/poetry install

    - name: Check code formatting by black
      run: |
        $POETRY_HOME/bin/poetry run black --check --verbose .

    - name: Lint code by ruff
      run: |
        $POETRY_HOME/bin/poetry run ruff .

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_EMAIL__LOGIN: ${{ secrets.EMAIL_LOGIN }}
        envkey_EMAIL__PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        file_name: dev.env
        fail_on_empty: false

    - name: Project Run
      run: |
        docker compose --env-file dev.env up --build

    - name: tests run
      run: |
        docker compose exec web bash
        pytest -v -s
